# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gateway.proto',
  package='protocol',
  syntax='proto3',
  serialized_pb=_b('\n\rgateway.proto\x12\x08protocol\"4\n\x0b\x43MD_GATEWAY\"%\n\x04\x45NUM\x12\x0b\n\x07INVALID\x10\x00\x12\x10\n\x0cVERIFY_TOKEN\x10\x01\"T\n\x1f\x45NUM_GATEWAY_VERIFY_TOKEN_ERROR\"1\n\x04\x45NUM\x12\x06\n\x02OK\x10\x00\x12\x0f\n\x0bVERIFY_FAIL\x10\x01\x12\x10\n\x0cSYSTEM_ERROR\x10\x02\":\n\x18MSG_GATEWAY_VERIFY_TOKEN\x12\x0f\n\x07\x41\x63\x63ount\x18\x01 \x01(\t\x12\r\n\x05Token\x18\x02 \x01(\t\"^\n\x1fMSG_GATEWAY_VERIFY_TOKEN_RESULT\x12;\n\x03\x45rr\x18\x01 \x01(\x0e\x32..protocol.ENUM_GATEWAY_VERIFY_TOKEN_ERROR.ENUMb\x06proto3')
)



_CMD_GATEWAY_ENUM = _descriptor.EnumDescriptor(
  name='ENUM',
  full_name='protocol.CMD_GATEWAY.ENUM',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERIFY_TOKEN', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=42,
  serialized_end=79,
)
_sym_db.RegisterEnumDescriptor(_CMD_GATEWAY_ENUM)

_ENUM_GATEWAY_VERIFY_TOKEN_ERROR_ENUM = _descriptor.EnumDescriptor(
  name='ENUM',
  full_name='protocol.ENUM_GATEWAY_VERIFY_TOKEN_ERROR.ENUM',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERIFY_FAIL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYSTEM_ERROR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=116,
  serialized_end=165,
)
_sym_db.RegisterEnumDescriptor(_ENUM_GATEWAY_VERIFY_TOKEN_ERROR_ENUM)


_CMD_GATEWAY = _descriptor.Descriptor(
  name='CMD_GATEWAY',
  full_name='protocol.CMD_GATEWAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CMD_GATEWAY_ENUM,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=79,
)


_ENUM_GATEWAY_VERIFY_TOKEN_ERROR = _descriptor.Descriptor(
  name='ENUM_GATEWAY_VERIFY_TOKEN_ERROR',
  full_name='protocol.ENUM_GATEWAY_VERIFY_TOKEN_ERROR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENUM_GATEWAY_VERIFY_TOKEN_ERROR_ENUM,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=165,
)


_MSG_GATEWAY_VERIFY_TOKEN = _descriptor.Descriptor(
  name='MSG_GATEWAY_VERIFY_TOKEN',
  full_name='protocol.MSG_GATEWAY_VERIFY_TOKEN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Account', full_name='protocol.MSG_GATEWAY_VERIFY_TOKEN.Account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Token', full_name='protocol.MSG_GATEWAY_VERIFY_TOKEN.Token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=225,
)


_MSG_GATEWAY_VERIFY_TOKEN_RESULT = _descriptor.Descriptor(
  name='MSG_GATEWAY_VERIFY_TOKEN_RESULT',
  full_name='protocol.MSG_GATEWAY_VERIFY_TOKEN_RESULT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Err', full_name='protocol.MSG_GATEWAY_VERIFY_TOKEN_RESULT.Err', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=321,
)

_CMD_GATEWAY_ENUM.containing_type = _CMD_GATEWAY
_ENUM_GATEWAY_VERIFY_TOKEN_ERROR_ENUM.containing_type = _ENUM_GATEWAY_VERIFY_TOKEN_ERROR
_MSG_GATEWAY_VERIFY_TOKEN_RESULT.fields_by_name['Err'].enum_type = _ENUM_GATEWAY_VERIFY_TOKEN_ERROR_ENUM
DESCRIPTOR.message_types_by_name['CMD_GATEWAY'] = _CMD_GATEWAY
DESCRIPTOR.message_types_by_name['ENUM_GATEWAY_VERIFY_TOKEN_ERROR'] = _ENUM_GATEWAY_VERIFY_TOKEN_ERROR
DESCRIPTOR.message_types_by_name['MSG_GATEWAY_VERIFY_TOKEN'] = _MSG_GATEWAY_VERIFY_TOKEN
DESCRIPTOR.message_types_by_name['MSG_GATEWAY_VERIFY_TOKEN_RESULT'] = _MSG_GATEWAY_VERIFY_TOKEN_RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CMD_GATEWAY = _reflection.GeneratedProtocolMessageType('CMD_GATEWAY', (_message.Message,), dict(
  DESCRIPTOR = _CMD_GATEWAY,
  __module__ = 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:protocol.CMD_GATEWAY)
  ))
_sym_db.RegisterMessage(CMD_GATEWAY)

ENUM_GATEWAY_VERIFY_TOKEN_ERROR = _reflection.GeneratedProtocolMessageType('ENUM_GATEWAY_VERIFY_TOKEN_ERROR', (_message.Message,), dict(
  DESCRIPTOR = _ENUM_GATEWAY_VERIFY_TOKEN_ERROR,
  __module__ = 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:protocol.ENUM_GATEWAY_VERIFY_TOKEN_ERROR)
  ))
_sym_db.RegisterMessage(ENUM_GATEWAY_VERIFY_TOKEN_ERROR)

MSG_GATEWAY_VERIFY_TOKEN = _reflection.GeneratedProtocolMessageType('MSG_GATEWAY_VERIFY_TOKEN', (_message.Message,), dict(
  DESCRIPTOR = _MSG_GATEWAY_VERIFY_TOKEN,
  __module__ = 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:protocol.MSG_GATEWAY_VERIFY_TOKEN)
  ))
_sym_db.RegisterMessage(MSG_GATEWAY_VERIFY_TOKEN)

MSG_GATEWAY_VERIFY_TOKEN_RESULT = _reflection.GeneratedProtocolMessageType('MSG_GATEWAY_VERIFY_TOKEN_RESULT', (_message.Message,), dict(
  DESCRIPTOR = _MSG_GATEWAY_VERIFY_TOKEN_RESULT,
  __module__ = 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:protocol.MSG_GATEWAY_VERIFY_TOKEN_RESULT)
  ))
_sym_db.RegisterMessage(MSG_GATEWAY_VERIFY_TOKEN_RESULT)


# @@protoc_insertion_point(module_scope)
