# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lobby.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol.lobby_custom_pb2 as lobby__custom__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lobby.proto',
  package='protocol',
  syntax='proto3',
  serialized_pb=_b('\n\x0blobby.proto\x12\x08protocol\x1a\x12lobby_custom.proto\"_\n\tCMD_LOBBY\"R\n\x04\x45NUM\x12\x0b\n\x07INVALID\x10\x00\x12\t\n\x05LOGIN\x10\x01\x12\x0f\n\x0b\x43REATE_ROLE\x10\x02\x12\x0e\n\nENTER_GAME\x10\x03\x12\x11\n\x0cMSGCMDOFFSET\x10\xa0\x1f\";\n\x17\x45NUM_LOBBY_COMMON_ERROR\" \n\x04\x45NUM\x12\x06\n\x02OK\x10\x00\x12\x10\n\x0cSYSTEM_ERROR\x10\x01\"\x11\n\x0fMSG_LOBBY_LOGIN\"v\n\x16MSG_LOBBY_LOGIN_RESULT\x12\x33\n\x03\x45rr\x18\x01 \x01(\x0e\x32&.protocol.ENUM_LOBBY_COMMON_ERROR.ENUM\x12\'\n\x05Roles\x18\x02 \x03(\x0b\x32\x18.protocol.ROLE_BASE_INFO\"M\n\x15MSG_LOBBY_CREATE_ROLE\x12\x0c\n\x04Slot\x18\x01 \x01(\r\x12&\n\x04Info\x18\x02 \x01(\x0b\x32\x18.protocol.ROLE_BASE_INFO\"S\n\x1cMSG_LOBBY_CREATE_ROLE_RESULT\x12\x33\n\x03\x45rr\x18\x01 \x01(\x0e\x32&.protocol.ENUM_LOBBY_COMMON_ERROR.ENUM\"$\n\x14MSG_LOBBY_ENTER_GAME\x12\x0c\n\x04Slot\x18\x01 \x01(\r\"\x82\x01\n\x1bMSG_LOBBY_ENTER_GAME_RESULT\x12\x33\n\x03\x45rr\x18\x01 \x01(\x0e\x32&.protocol.ENUM_LOBBY_COMMON_ERROR.ENUM\x12.\n\nDetailInfo\x18\x02 \x01(\x0b\x32\x1a.protocol.ROLE_DETAIL_INFOb\x06proto3')
  ,
  dependencies=[lobby__custom__pb2.DESCRIPTOR,])



_CMD_LOBBY_ENUM = _descriptor.EnumDescriptor(
  name='ENUM',
  full_name='protocol.CMD_LOBBY.ENUM',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGIN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_ROLE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTER_GAME', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSGCMDOFFSET', index=4, number=4000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=58,
  serialized_end=140,
)
_sym_db.RegisterEnumDescriptor(_CMD_LOBBY_ENUM)

_ENUM_LOBBY_COMMON_ERROR_ENUM = _descriptor.EnumDescriptor(
  name='ENUM',
  full_name='protocol.ENUM_LOBBY_COMMON_ERROR.ENUM',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYSTEM_ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=169,
  serialized_end=201,
)
_sym_db.RegisterEnumDescriptor(_ENUM_LOBBY_COMMON_ERROR_ENUM)


_CMD_LOBBY = _descriptor.Descriptor(
  name='CMD_LOBBY',
  full_name='protocol.CMD_LOBBY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CMD_LOBBY_ENUM,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=140,
)


_ENUM_LOBBY_COMMON_ERROR = _descriptor.Descriptor(
  name='ENUM_LOBBY_COMMON_ERROR',
  full_name='protocol.ENUM_LOBBY_COMMON_ERROR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENUM_LOBBY_COMMON_ERROR_ENUM,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=201,
)


_MSG_LOBBY_LOGIN = _descriptor.Descriptor(
  name='MSG_LOBBY_LOGIN',
  full_name='protocol.MSG_LOBBY_LOGIN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=220,
)


_MSG_LOBBY_LOGIN_RESULT = _descriptor.Descriptor(
  name='MSG_LOBBY_LOGIN_RESULT',
  full_name='protocol.MSG_LOBBY_LOGIN_RESULT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Err', full_name='protocol.MSG_LOBBY_LOGIN_RESULT.Err', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Roles', full_name='protocol.MSG_LOBBY_LOGIN_RESULT.Roles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=340,
)


_MSG_LOBBY_CREATE_ROLE = _descriptor.Descriptor(
  name='MSG_LOBBY_CREATE_ROLE',
  full_name='protocol.MSG_LOBBY_CREATE_ROLE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Slot', full_name='protocol.MSG_LOBBY_CREATE_ROLE.Slot', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Info', full_name='protocol.MSG_LOBBY_CREATE_ROLE.Info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=419,
)


_MSG_LOBBY_CREATE_ROLE_RESULT = _descriptor.Descriptor(
  name='MSG_LOBBY_CREATE_ROLE_RESULT',
  full_name='protocol.MSG_LOBBY_CREATE_ROLE_RESULT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Err', full_name='protocol.MSG_LOBBY_CREATE_ROLE_RESULT.Err', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=504,
)


_MSG_LOBBY_ENTER_GAME = _descriptor.Descriptor(
  name='MSG_LOBBY_ENTER_GAME',
  full_name='protocol.MSG_LOBBY_ENTER_GAME',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Slot', full_name='protocol.MSG_LOBBY_ENTER_GAME.Slot', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=542,
)


_MSG_LOBBY_ENTER_GAME_RESULT = _descriptor.Descriptor(
  name='MSG_LOBBY_ENTER_GAME_RESULT',
  full_name='protocol.MSG_LOBBY_ENTER_GAME_RESULT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Err', full_name='protocol.MSG_LOBBY_ENTER_GAME_RESULT.Err', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DetailInfo', full_name='protocol.MSG_LOBBY_ENTER_GAME_RESULT.DetailInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=545,
  serialized_end=675,
)

_CMD_LOBBY_ENUM.containing_type = _CMD_LOBBY
_ENUM_LOBBY_COMMON_ERROR_ENUM.containing_type = _ENUM_LOBBY_COMMON_ERROR
_MSG_LOBBY_LOGIN_RESULT.fields_by_name['Err'].enum_type = _ENUM_LOBBY_COMMON_ERROR_ENUM
_MSG_LOBBY_LOGIN_RESULT.fields_by_name['Roles'].message_type = lobby__custom__pb2._ROLE_BASE_INFO
_MSG_LOBBY_CREATE_ROLE.fields_by_name['Info'].message_type = lobby__custom__pb2._ROLE_BASE_INFO
_MSG_LOBBY_CREATE_ROLE_RESULT.fields_by_name['Err'].enum_type = _ENUM_LOBBY_COMMON_ERROR_ENUM
_MSG_LOBBY_ENTER_GAME_RESULT.fields_by_name['Err'].enum_type = _ENUM_LOBBY_COMMON_ERROR_ENUM
_MSG_LOBBY_ENTER_GAME_RESULT.fields_by_name['DetailInfo'].message_type = lobby__custom__pb2._ROLE_DETAIL_INFO
DESCRIPTOR.message_types_by_name['CMD_LOBBY'] = _CMD_LOBBY
DESCRIPTOR.message_types_by_name['ENUM_LOBBY_COMMON_ERROR'] = _ENUM_LOBBY_COMMON_ERROR
DESCRIPTOR.message_types_by_name['MSG_LOBBY_LOGIN'] = _MSG_LOBBY_LOGIN
DESCRIPTOR.message_types_by_name['MSG_LOBBY_LOGIN_RESULT'] = _MSG_LOBBY_LOGIN_RESULT
DESCRIPTOR.message_types_by_name['MSG_LOBBY_CREATE_ROLE'] = _MSG_LOBBY_CREATE_ROLE
DESCRIPTOR.message_types_by_name['MSG_LOBBY_CREATE_ROLE_RESULT'] = _MSG_LOBBY_CREATE_ROLE_RESULT
DESCRIPTOR.message_types_by_name['MSG_LOBBY_ENTER_GAME'] = _MSG_LOBBY_ENTER_GAME
DESCRIPTOR.message_types_by_name['MSG_LOBBY_ENTER_GAME_RESULT'] = _MSG_LOBBY_ENTER_GAME_RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CMD_LOBBY = _reflection.GeneratedProtocolMessageType('CMD_LOBBY', (_message.Message,), dict(
  DESCRIPTOR = _CMD_LOBBY,
  __module__ = 'lobby_pb2'
  # @@protoc_insertion_point(class_scope:protocol.CMD_LOBBY)
  ))
_sym_db.RegisterMessage(CMD_LOBBY)

ENUM_LOBBY_COMMON_ERROR = _reflection.GeneratedProtocolMessageType('ENUM_LOBBY_COMMON_ERROR', (_message.Message,), dict(
  DESCRIPTOR = _ENUM_LOBBY_COMMON_ERROR,
  __module__ = 'lobby_pb2'
  # @@protoc_insertion_point(class_scope:protocol.ENUM_LOBBY_COMMON_ERROR)
  ))
_sym_db.RegisterMessage(ENUM_LOBBY_COMMON_ERROR)

MSG_LOBBY_LOGIN = _reflection.GeneratedProtocolMessageType('MSG_LOBBY_LOGIN', (_message.Message,), dict(
  DESCRIPTOR = _MSG_LOBBY_LOGIN,
  __module__ = 'lobby_pb2'
  # @@protoc_insertion_point(class_scope:protocol.MSG_LOBBY_LOGIN)
  ))
_sym_db.RegisterMessage(MSG_LOBBY_LOGIN)

MSG_LOBBY_LOGIN_RESULT = _reflection.GeneratedProtocolMessageType('MSG_LOBBY_LOGIN_RESULT', (_message.Message,), dict(
  DESCRIPTOR = _MSG_LOBBY_LOGIN_RESULT,
  __module__ = 'lobby_pb2'
  # @@protoc_insertion_point(class_scope:protocol.MSG_LOBBY_LOGIN_RESULT)
  ))
_sym_db.RegisterMessage(MSG_LOBBY_LOGIN_RESULT)

MSG_LOBBY_CREATE_ROLE = _reflection.GeneratedProtocolMessageType('MSG_LOBBY_CREATE_ROLE', (_message.Message,), dict(
  DESCRIPTOR = _MSG_LOBBY_CREATE_ROLE,
  __module__ = 'lobby_pb2'
  # @@protoc_insertion_point(class_scope:protocol.MSG_LOBBY_CREATE_ROLE)
  ))
_sym_db.RegisterMessage(MSG_LOBBY_CREATE_ROLE)

MSG_LOBBY_CREATE_ROLE_RESULT = _reflection.GeneratedProtocolMessageType('MSG_LOBBY_CREATE_ROLE_RESULT', (_message.Message,), dict(
  DESCRIPTOR = _MSG_LOBBY_CREATE_ROLE_RESULT,
  __module__ = 'lobby_pb2'
  # @@protoc_insertion_point(class_scope:protocol.MSG_LOBBY_CREATE_ROLE_RESULT)
  ))
_sym_db.RegisterMessage(MSG_LOBBY_CREATE_ROLE_RESULT)

MSG_LOBBY_ENTER_GAME = _reflection.GeneratedProtocolMessageType('MSG_LOBBY_ENTER_GAME', (_message.Message,), dict(
  DESCRIPTOR = _MSG_LOBBY_ENTER_GAME,
  __module__ = 'lobby_pb2'
  # @@protoc_insertion_point(class_scope:protocol.MSG_LOBBY_ENTER_GAME)
  ))
_sym_db.RegisterMessage(MSG_LOBBY_ENTER_GAME)

MSG_LOBBY_ENTER_GAME_RESULT = _reflection.GeneratedProtocolMessageType('MSG_LOBBY_ENTER_GAME_RESULT', (_message.Message,), dict(
  DESCRIPTOR = _MSG_LOBBY_ENTER_GAME_RESULT,
  __module__ = 'lobby_pb2'
  # @@protoc_insertion_point(class_scope:protocol.MSG_LOBBY_ENTER_GAME_RESULT)
  ))
_sym_db.RegisterMessage(MSG_LOBBY_ENTER_GAME_RESULT)


# @@protoc_insertion_point(module_scope)
