# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lobby_custom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lobby_custom.proto',
  package='protocol',
  syntax='proto3',
  serialized_pb=_b('\n\x12lobby_custom.proto\x12\x08protocol\"2\n\x0eROLE_BASE_INFO\x12\x0e\n\x06RoleID\x18\x01 \x01(\x04\x12\x10\n\x08RoleName\x18\x02 \x01(\t\">\n\x10ROLE_DETAIL_INFO\x12*\n\x08\x42\x61seInfo\x18\x01 \x01(\x0b\x32\x18.protocol.ROLE_BASE_INFOb\x06proto3')
)




_ROLE_BASE_INFO = _descriptor.Descriptor(
  name='ROLE_BASE_INFO',
  full_name='protocol.ROLE_BASE_INFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RoleID', full_name='protocol.ROLE_BASE_INFO.RoleID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RoleName', full_name='protocol.ROLE_BASE_INFO.RoleName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=82,
)


_ROLE_DETAIL_INFO = _descriptor.Descriptor(
  name='ROLE_DETAIL_INFO',
  full_name='protocol.ROLE_DETAIL_INFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='BaseInfo', full_name='protocol.ROLE_DETAIL_INFO.BaseInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=146,
)

_ROLE_DETAIL_INFO.fields_by_name['BaseInfo'].message_type = _ROLE_BASE_INFO
DESCRIPTOR.message_types_by_name['ROLE_BASE_INFO'] = _ROLE_BASE_INFO
DESCRIPTOR.message_types_by_name['ROLE_DETAIL_INFO'] = _ROLE_DETAIL_INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ROLE_BASE_INFO = _reflection.GeneratedProtocolMessageType('ROLE_BASE_INFO', (_message.Message,), dict(
  DESCRIPTOR = _ROLE_BASE_INFO,
  __module__ = 'lobby_custom_pb2'
  # @@protoc_insertion_point(class_scope:protocol.ROLE_BASE_INFO)
  ))
_sym_db.RegisterMessage(ROLE_BASE_INFO)

ROLE_DETAIL_INFO = _reflection.GeneratedProtocolMessageType('ROLE_DETAIL_INFO', (_message.Message,), dict(
  DESCRIPTOR = _ROLE_DETAIL_INFO,
  __module__ = 'lobby_custom_pb2'
  # @@protoc_insertion_point(class_scope:protocol.ROLE_DETAIL_INFO)
  ))
_sym_db.RegisterMessage(ROLE_DETAIL_INFO)


# @@protoc_insertion_point(module_scope)
