// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gateway.proto

package protocol

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CMD_GW_ENUM int32

const (
	CMD_GW_INVALID           CMD_GW_ENUM = 0
	CMD_GW_PING              CMD_GW_ENUM = 1
	CMD_GW_REGISTER_SERVER   CMD_GW_ENUM = 2
	CMD_GW_LOSE_SERVER       CMD_GW_ENUM = 3
	CMD_GW_REGISTER_ACCOUNT  CMD_GW_ENUM = 4
	CMD_GW_RELAY_CLIENT_MSG  CMD_GW_ENUM = 5
	CMD_GW_LOSE_ACCOUNT      CMD_GW_ENUM = 6
	CMD_GW_RELAY_SERVER_MSG1 CMD_GW_ENUM = 7
	CMD_GW_RELAY_SERVER_MSG2 CMD_GW_ENUM = 8
)

var CMD_GW_ENUM_name = map[int32]string{
	0: "INVALID",
	1: "PING",
	2: "REGISTER_SERVER",
	3: "LOSE_SERVER",
	4: "REGISTER_ACCOUNT",
	5: "RELAY_CLIENT_MSG",
	6: "LOSE_ACCOUNT",
	7: "RELAY_SERVER_MSG1",
	8: "RELAY_SERVER_MSG2",
}
var CMD_GW_ENUM_value = map[string]int32{
	"INVALID":           0,
	"PING":              1,
	"REGISTER_SERVER":   2,
	"LOSE_SERVER":       3,
	"REGISTER_ACCOUNT":  4,
	"RELAY_CLIENT_MSG":  5,
	"LOSE_ACCOUNT":      6,
	"RELAY_SERVER_MSG1": 7,
	"RELAY_SERVER_MSG2": 8,
}

func (x CMD_GW_ENUM) String() string {
	return proto.EnumName(CMD_GW_ENUM_name, int32(x))
}
func (CMD_GW_ENUM) EnumDescriptor() ([]byte, []int) { return fileDescriptorGateway, []int{0, 0} }

type RELAY_SERVER_MSG_TYPE_ENUM int32

const (
	RELAY_SERVER_MSG_TYPE_BROADCAST RELAY_SERVER_MSG_TYPE_ENUM = 0
	RELAY_SERVER_MSG_TYPE_RANDOM    RELAY_SERVER_MSG_TYPE_ENUM = 1
)

var RELAY_SERVER_MSG_TYPE_ENUM_name = map[int32]string{
	0: "BROADCAST",
	1: "RANDOM",
}
var RELAY_SERVER_MSG_TYPE_ENUM_value = map[string]int32{
	"BROADCAST": 0,
	"RANDOM":    1,
}

func (x RELAY_SERVER_MSG_TYPE_ENUM) String() string {
	return proto.EnumName(RELAY_SERVER_MSG_TYPE_ENUM_name, int32(x))
}
func (RELAY_SERVER_MSG_TYPE_ENUM) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorGateway, []int{4, 0}
}

type CMD_GW struct {
}

func (m *CMD_GW) Reset()                    { *m = CMD_GW{} }
func (m *CMD_GW) String() string            { return proto.CompactTextString(m) }
func (*CMD_GW) ProtoMessage()               {}
func (*CMD_GW) Descriptor() ([]byte, []int) { return fileDescriptorGateway, []int{0} }

// 注册账号 ( GATEWAY -> S )。只通知账号对应分配的服务
type MSG_GW_REGISTER_ACCOUNT struct {
	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
}

func (m *MSG_GW_REGISTER_ACCOUNT) Reset()                    { *m = MSG_GW_REGISTER_ACCOUNT{} }
func (m *MSG_GW_REGISTER_ACCOUNT) String() string            { return proto.CompactTextString(m) }
func (*MSG_GW_REGISTER_ACCOUNT) ProtoMessage()               {}
func (*MSG_GW_REGISTER_ACCOUNT) Descriptor() ([]byte, []int) { return fileDescriptorGateway, []int{1} }

func (m *MSG_GW_REGISTER_ACCOUNT) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// 中继客户端消息 ( GATEWAY -> S / S -> GATEWAY )
type MSG_GW_RELAY_CLIENT_MSG struct {
	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	CMD     uint32 `protobuf:"varint,2,opt,name=CMD,proto3" json:"CMD,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *MSG_GW_RELAY_CLIENT_MSG) Reset()                    { *m = MSG_GW_RELAY_CLIENT_MSG{} }
func (m *MSG_GW_RELAY_CLIENT_MSG) String() string            { return proto.CompactTextString(m) }
func (*MSG_GW_RELAY_CLIENT_MSG) ProtoMessage()               {}
func (*MSG_GW_RELAY_CLIENT_MSG) Descriptor() ([]byte, []int) { return fileDescriptorGateway, []int{2} }

func (m *MSG_GW_RELAY_CLIENT_MSG) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *MSG_GW_RELAY_CLIENT_MSG) GetCMD() uint32 {
	if m != nil {
		return m.CMD
	}
	return 0
}

func (m *MSG_GW_RELAY_CLIENT_MSG) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 丢失账号 ( GATEWAY -> S )。只通知账号对应分配的服务
type MSG_GW_LOSE_ACCOUNT struct {
	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
}

func (m *MSG_GW_LOSE_ACCOUNT) Reset()                    { *m = MSG_GW_LOSE_ACCOUNT{} }
func (m *MSG_GW_LOSE_ACCOUNT) String() string            { return proto.CompactTextString(m) }
func (*MSG_GW_LOSE_ACCOUNT) ProtoMessage()               {}
func (*MSG_GW_LOSE_ACCOUNT) Descriptor() ([]byte, []int) { return fileDescriptorGateway, []int{3} }

func (m *MSG_GW_LOSE_ACCOUNT) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// 中继服务器消息 ( S -> GATEWAY -> S)
type RELAY_SERVER_MSG_TYPE struct {
}

func (m *RELAY_SERVER_MSG_TYPE) Reset()                    { *m = RELAY_SERVER_MSG_TYPE{} }
func (m *RELAY_SERVER_MSG_TYPE) String() string            { return proto.CompactTextString(m) }
func (*RELAY_SERVER_MSG_TYPE) ProtoMessage()               {}
func (*RELAY_SERVER_MSG_TYPE) Descriptor() ([]byte, []int) { return fileDescriptorGateway, []int{4} }

type MSG_GW_RELAY_SERVER_MSG1 struct {
	SourceID   *SERVER_ID                 `protobuf:"bytes,1,opt,name=SourceID" json:"SourceID,omitempty"`
	SourceType uint32                     `protobuf:"varint,2,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	TargetType uint32                     `protobuf:"varint,3,opt,name=TargetType,proto3" json:"TargetType,omitempty"`
	SendType   RELAY_SERVER_MSG_TYPE_ENUM `protobuf:"varint,4,opt,name=SendType,proto3,enum=protocol.RELAY_SERVER_MSG_TYPE_ENUM" json:"SendType,omitempty"`
	CMD        uint32                     `protobuf:"varint,5,opt,name=CMD,proto3" json:"CMD,omitempty"`
	Data       []byte                     `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *MSG_GW_RELAY_SERVER_MSG1) Reset()                    { *m = MSG_GW_RELAY_SERVER_MSG1{} }
func (m *MSG_GW_RELAY_SERVER_MSG1) String() string            { return proto.CompactTextString(m) }
func (*MSG_GW_RELAY_SERVER_MSG1) ProtoMessage()               {}
func (*MSG_GW_RELAY_SERVER_MSG1) Descriptor() ([]byte, []int) { return fileDescriptorGateway, []int{5} }

func (m *MSG_GW_RELAY_SERVER_MSG1) GetSourceID() *SERVER_ID {
	if m != nil {
		return m.SourceID
	}
	return nil
}

func (m *MSG_GW_RELAY_SERVER_MSG1) GetSourceType() uint32 {
	if m != nil {
		return m.SourceType
	}
	return 0
}

func (m *MSG_GW_RELAY_SERVER_MSG1) GetTargetType() uint32 {
	if m != nil {
		return m.TargetType
	}
	return 0
}

func (m *MSG_GW_RELAY_SERVER_MSG1) GetSendType() RELAY_SERVER_MSG_TYPE_ENUM {
	if m != nil {
		return m.SendType
	}
	return RELAY_SERVER_MSG_TYPE_BROADCAST
}

func (m *MSG_GW_RELAY_SERVER_MSG1) GetCMD() uint32 {
	if m != nil {
		return m.CMD
	}
	return 0
}

func (m *MSG_GW_RELAY_SERVER_MSG1) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 中继服务器消息 ( S -> GATEWAY -> S)
type MSG_GW_RELAY_SERVER_MSG2 struct {
	SourceID   *SERVER_ID `protobuf:"bytes,1,opt,name=SourceID" json:"SourceID,omitempty"`
	SourceType uint32     `protobuf:"varint,2,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	TargetID   *SERVER_ID `protobuf:"bytes,3,opt,name=TargetID" json:"TargetID,omitempty"`
	CMD        uint32     `protobuf:"varint,4,opt,name=CMD,proto3" json:"CMD,omitempty"`
	Data       []byte     `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *MSG_GW_RELAY_SERVER_MSG2) Reset()                    { *m = MSG_GW_RELAY_SERVER_MSG2{} }
func (m *MSG_GW_RELAY_SERVER_MSG2) String() string            { return proto.CompactTextString(m) }
func (*MSG_GW_RELAY_SERVER_MSG2) ProtoMessage()               {}
func (*MSG_GW_RELAY_SERVER_MSG2) Descriptor() ([]byte, []int) { return fileDescriptorGateway, []int{6} }

func (m *MSG_GW_RELAY_SERVER_MSG2) GetSourceID() *SERVER_ID {
	if m != nil {
		return m.SourceID
	}
	return nil
}

func (m *MSG_GW_RELAY_SERVER_MSG2) GetSourceType() uint32 {
	if m != nil {
		return m.SourceType
	}
	return 0
}

func (m *MSG_GW_RELAY_SERVER_MSG2) GetTargetID() *SERVER_ID {
	if m != nil {
		return m.TargetID
	}
	return nil
}

func (m *MSG_GW_RELAY_SERVER_MSG2) GetCMD() uint32 {
	if m != nil {
		return m.CMD
	}
	return 0
}

func (m *MSG_GW_RELAY_SERVER_MSG2) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CMD_GW)(nil), "protocol.CMD_GW")
	proto.RegisterType((*MSG_GW_REGISTER_ACCOUNT)(nil), "protocol.MSG_GW_REGISTER_ACCOUNT")
	proto.RegisterType((*MSG_GW_RELAY_CLIENT_MSG)(nil), "protocol.MSG_GW_RELAY_CLIENT_MSG")
	proto.RegisterType((*MSG_GW_LOSE_ACCOUNT)(nil), "protocol.MSG_GW_LOSE_ACCOUNT")
	proto.RegisterType((*RELAY_SERVER_MSG_TYPE)(nil), "protocol.RELAY_SERVER_MSG_TYPE")
	proto.RegisterType((*MSG_GW_RELAY_SERVER_MSG1)(nil), "protocol.MSG_GW_RELAY_SERVER_MSG1")
	proto.RegisterType((*MSG_GW_RELAY_SERVER_MSG2)(nil), "protocol.MSG_GW_RELAY_SERVER_MSG2")
	proto.RegisterEnum("protocol.CMD_GW_ENUM", CMD_GW_ENUM_name, CMD_GW_ENUM_value)
	proto.RegisterEnum("protocol.RELAY_SERVER_MSG_TYPE_ENUM", RELAY_SERVER_MSG_TYPE_ENUM_name, RELAY_SERVER_MSG_TYPE_ENUM_value)
}
func (m *CMD_GW) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CMD_GW) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *MSG_GW_REGISTER_ACCOUNT) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MSG_GW_REGISTER_ACCOUNT) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Account) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGateway(dAtA, i, uint64(len(m.Account)))
		i += copy(dAtA[i:], m.Account)
	}
	return i, nil
}

func (m *MSG_GW_RELAY_CLIENT_MSG) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MSG_GW_RELAY_CLIENT_MSG) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Account) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGateway(dAtA, i, uint64(len(m.Account)))
		i += copy(dAtA[i:], m.Account)
	}
	if m.CMD != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGateway(dAtA, i, uint64(m.CMD))
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintGateway(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *MSG_GW_LOSE_ACCOUNT) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MSG_GW_LOSE_ACCOUNT) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Account) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGateway(dAtA, i, uint64(len(m.Account)))
		i += copy(dAtA[i:], m.Account)
	}
	return i, nil
}

func (m *RELAY_SERVER_MSG_TYPE) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RELAY_SERVER_MSG_TYPE) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *MSG_GW_RELAY_SERVER_MSG1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MSG_GW_RELAY_SERVER_MSG1) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SourceID != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGateway(dAtA, i, uint64(m.SourceID.Size()))
		n1, err := m.SourceID.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.SourceType != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGateway(dAtA, i, uint64(m.SourceType))
	}
	if m.TargetType != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGateway(dAtA, i, uint64(m.TargetType))
	}
	if m.SendType != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintGateway(dAtA, i, uint64(m.SendType))
	}
	if m.CMD != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintGateway(dAtA, i, uint64(m.CMD))
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintGateway(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *MSG_GW_RELAY_SERVER_MSG2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MSG_GW_RELAY_SERVER_MSG2) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SourceID != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGateway(dAtA, i, uint64(m.SourceID.Size()))
		n2, err := m.SourceID.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.SourceType != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGateway(dAtA, i, uint64(m.SourceType))
	}
	if m.TargetID != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintGateway(dAtA, i, uint64(m.TargetID.Size()))
		n3, err := m.TargetID.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.CMD != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintGateway(dAtA, i, uint64(m.CMD))
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintGateway(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func encodeFixed64Gateway(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Gateway(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintGateway(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CMD_GW) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *MSG_GW_REGISTER_ACCOUNT) Size() (n int) {
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovGateway(uint64(l))
	}
	return n
}

func (m *MSG_GW_RELAY_CLIENT_MSG) Size() (n int) {
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovGateway(uint64(l))
	}
	if m.CMD != 0 {
		n += 1 + sovGateway(uint64(m.CMD))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovGateway(uint64(l))
	}
	return n
}

func (m *MSG_GW_LOSE_ACCOUNT) Size() (n int) {
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovGateway(uint64(l))
	}
	return n
}

func (m *RELAY_SERVER_MSG_TYPE) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *MSG_GW_RELAY_SERVER_MSG1) Size() (n int) {
	var l int
	_ = l
	if m.SourceID != nil {
		l = m.SourceID.Size()
		n += 1 + l + sovGateway(uint64(l))
	}
	if m.SourceType != 0 {
		n += 1 + sovGateway(uint64(m.SourceType))
	}
	if m.TargetType != 0 {
		n += 1 + sovGateway(uint64(m.TargetType))
	}
	if m.SendType != 0 {
		n += 1 + sovGateway(uint64(m.SendType))
	}
	if m.CMD != 0 {
		n += 1 + sovGateway(uint64(m.CMD))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovGateway(uint64(l))
	}
	return n
}

func (m *MSG_GW_RELAY_SERVER_MSG2) Size() (n int) {
	var l int
	_ = l
	if m.SourceID != nil {
		l = m.SourceID.Size()
		n += 1 + l + sovGateway(uint64(l))
	}
	if m.SourceType != 0 {
		n += 1 + sovGateway(uint64(m.SourceType))
	}
	if m.TargetID != nil {
		l = m.TargetID.Size()
		n += 1 + l + sovGateway(uint64(l))
	}
	if m.CMD != 0 {
		n += 1 + sovGateway(uint64(m.CMD))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovGateway(uint64(l))
	}
	return n
}

func sovGateway(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGateway(x uint64) (n int) {
	return sovGateway(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CMD_GW) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CMD_GW: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CMD_GW: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MSG_GW_REGISTER_ACCOUNT) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MSG_GW_REGISTER_ACCOUNT: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MSG_GW_REGISTER_ACCOUNT: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MSG_GW_RELAY_CLIENT_MSG) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MSG_GW_RELAY_CLIENT_MSG: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MSG_GW_RELAY_CLIENT_MSG: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CMD", wireType)
			}
			m.CMD = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CMD |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MSG_GW_LOSE_ACCOUNT) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MSG_GW_LOSE_ACCOUNT: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MSG_GW_LOSE_ACCOUNT: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RELAY_SERVER_MSG_TYPE) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RELAY_SERVER_MSG_TYPE: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RELAY_SERVER_MSG_TYPE: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MSG_GW_RELAY_SERVER_MSG1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MSG_GW_RELAY_SERVER_MSG1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MSG_GW_RELAY_SERVER_MSG1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SourceID == nil {
				m.SourceID = &SERVER_ID{}
			}
			if err := m.SourceID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceType", wireType)
			}
			m.SourceType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourceType |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetType", wireType)
			}
			m.TargetType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetType |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendType", wireType)
			}
			m.SendType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SendType |= (RELAY_SERVER_MSG_TYPE_ENUM(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CMD", wireType)
			}
			m.CMD = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CMD |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MSG_GW_RELAY_SERVER_MSG2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MSG_GW_RELAY_SERVER_MSG2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MSG_GW_RELAY_SERVER_MSG2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SourceID == nil {
				m.SourceID = &SERVER_ID{}
			}
			if err := m.SourceID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceType", wireType)
			}
			m.SourceType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourceType |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TargetID == nil {
				m.TargetID = &SERVER_ID{}
			}
			if err := m.TargetID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CMD", wireType)
			}
			m.CMD = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CMD |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGateway(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthGateway
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGateway
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGateway(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGateway = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGateway   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("gateway.proto", fileDescriptorGateway) }

var fileDescriptorGateway = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xbd, 0x6e, 0xd3, 0x50,
	0x14, 0xc7, 0x73, 0x1b, 0xc7, 0x71, 0x4f, 0x12, 0x7a, 0x39, 0xa1, 0xc2, 0x62, 0xb0, 0x82, 0xc5,
	0x90, 0x29, 0x11, 0xe9, 0xc6, 0x84, 0xeb, 0x6b, 0x59, 0x57, 0x8a, 0x9d, 0xea, 0x5e, 0xb7, 0x55,
	0x26, 0xcb, 0x18, 0xab, 0x0b, 0x8d, 0xab, 0xc8, 0x15, 0xea, 0x5b, 0xf0, 0x26, 0xec, 0x8c, 0x4c,
	0x8c, 0x3c, 0x02, 0x0a, 0x8f, 0xc0, 0x0b, 0xa0, 0x5c, 0xc7, 0x89, 0xfb, 0x11, 0x26, 0x26, 0x1f,
	0xff, 0xcf, 0xff, 0x7c, 0xfc, 0x8e, 0x0d, 0xbd, 0xab, 0xa4, 0xc8, 0x3e, 0x27, 0x77, 0xa3, 0x9b,
	0x65, 0x5e, 0xe4, 0x68, 0xa8, 0x47, 0x9a, 0x7f, 0x7a, 0xd5, 0x4d, 0xf3, 0xeb, 0xeb, 0x7c, 0x51,
	0xea, 0xf6, 0x37, 0x02, 0xba, 0x1b, 0xb0, 0xd8, 0xbf, 0xb4, 0xbf, 0x12, 0xd0, 0xbc, 0xf0, 0x3c,
	0xc0, 0x0e, 0xb4, 0x79, 0x78, 0xe1, 0x4c, 0x39, 0xa3, 0x0d, 0x34, 0x40, 0x3b, 0xe3, 0xa1, 0x4f,
	0x09, 0xf6, 0xe1, 0x48, 0x78, 0x3e, 0x97, 0x91, 0x27, 0x62, 0xe9, 0x89, 0x0b, 0x4f, 0xd0, 0x03,
	0x3c, 0x82, 0xce, 0x74, 0x26, 0xbd, 0x4a, 0x68, 0xe2, 0x0b, 0xa0, 0x5b, 0x97, 0xe3, 0xba, 0xb3,
	0xf3, 0x30, 0xa2, 0x5a, 0xa9, 0x4e, 0x9d, 0x79, 0xec, 0x4e, 0xb9, 0x17, 0x46, 0x71, 0x20, 0x7d,
	0xda, 0x42, 0x0a, 0x5d, 0x55, 0x5c, 0xf9, 0x74, 0x3c, 0x86, 0xe7, 0xa5, 0xaf, 0xec, 0xb7, 0xf6,
	0xbd, 0xa5, 0xed, 0xa7, 0xe4, 0x09, 0x35, 0xec, 0x13, 0x78, 0x19, 0x48, 0x3f, 0xf6, 0x2f, 0xe3,
	0x87, 0x23, 0xd1, 0x84, 0xb6, 0x93, 0xa6, 0xf9, 0xed, 0xa2, 0x30, 0xc9, 0x80, 0x0c, 0x0f, 0x45,
	0xf5, 0x6a, 0xcf, 0x6b, 0x45, 0xf7, 0x37, 0xda, 0x5f, 0x84, 0x14, 0x9a, 0x6e, 0xc0, 0xcc, 0x83,
	0x01, 0x19, 0xf6, 0xc4, 0x3a, 0x44, 0x04, 0x8d, 0x25, 0x45, 0x62, 0x36, 0x07, 0x64, 0xd8, 0x15,
	0x2a, 0xb6, 0xc7, 0xd0, 0xdf, 0xb4, 0xae, 0x63, 0xfd, 0x63, 0x97, 0x77, 0x70, 0xfc, 0x90, 0x2b,
	0x8e, 0xe6, 0x67, 0x9e, 0xfd, 0x7a, 0xf3, 0x29, 0x7a, 0x70, 0x78, 0x2a, 0x66, 0x0e, 0x73, 0x1d,
	0x19, 0xd1, 0x06, 0x02, 0xe8, 0xc2, 0x09, 0xd9, 0x2c, 0xa0, 0xc4, 0xfe, 0x43, 0xc0, 0xbc, 0x07,
	0x52, 0x3b, 0x19, 0x8e, 0xc1, 0x90, 0xf9, 0xed, 0x32, 0xcd, 0x38, 0x53, 0x33, 0x3b, 0x93, 0xfe,
	0xa8, 0xfa, 0x03, 0x46, 0x1b, 0x23, 0x67, 0x62, 0x6b, 0x42, 0x0b, 0xa0, 0x8c, 0xa3, 0xbb, 0x9b,
	0x6c, 0xc3, 0x59, 0x53, 0xd6, 0xf9, 0x28, 0x59, 0x5e, 0x65, 0x85, 0xca, 0x37, 0xcb, 0xfc, 0x4e,
	0xc1, 0xf7, 0x60, 0xc8, 0x6c, 0xf1, 0x51, 0x65, 0xb5, 0x01, 0x19, 0x3e, 0x9b, 0xbc, 0xd9, 0x0d,
	0x7c, 0x92, 0x71, 0xb4, 0x06, 0x14, 0xdb, 0xaa, 0xea, 0xc4, 0xad, 0xc7, 0x27, 0xd6, 0x6b, 0x27,
	0xfe, 0xbe, 0x9f, 0x7a, 0xf2, 0xff, 0xa9, 0xc7, 0x60, 0x94, 0x8c, 0x9c, 0x29, 0xe6, 0x7d, 0x0d,
	0x2b, 0x53, 0x05, 0xa1, 0x3d, 0x86, 0x68, 0xed, 0x20, 0x4e, 0xe9, 0x8f, 0x95, 0x45, 0x7e, 0xae,
	0x2c, 0xf2, 0x6b, 0x65, 0x91, 0x2f, 0xbf, 0xad, 0xc6, 0x07, 0x5d, 0x75, 0x3d, 0xf9, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x83, 0xcd, 0x74, 0x39, 0xb6, 0x03, 0x00, 0x00,
}
